<?php

namespace App\Controller;

use App\Entity\Course;
use App\Entity\Category;
use App\Entity\CourseObject;
use App\Entity\Classroom;
use App\Entity\Documents;
use App\Entity\UserCourse;
use App\Entity\Comments;
use App\Entity\Files;
use App\Entity\Works;
use App\Entity\User;
use App\Repository\CategoryRepository;
use App\Repository\CourseRepository;
use App\Repository\ClassroomRepository;
use App\Repository\UserRepository;
use App\Repository\CourseObjectRepository;
use App\Repository\UserCourseRepository;
use App\Repository\WorksRepository;
use App\Repository\ProgramsRepository;
use App\Form\CategoryType;
use App\Form\CourseType;
use App\Form\ClassroomType;
use App\Form\CourseObjectType;
use App\Form\CommentsType;
use App\Form\WorksType;
use App\Events\WorkCreatedEvent;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Mime\MimeTypes;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\String\Slugger\SluggerInterface;


class CourseController extends AbstractController
{
	private $request;

	private $manager;

	private $categoryrepository;

	private $courserepository;

	private $classroomrepository;

	private $userrepository;

	private $objectrepository;

	private $usercourserepository;

	private $worksrepository;

	private $programsrepository;

	public function __construct(EntityManagerInterface $manager, CategoryRepository $categoryrepository, CourseRepository $courserepository, ClassroomRepository $classroomrepository, UserRepository $userrepository, CourseObjectRepository $objectrepository, UserCourseRepository $usercourserepository, WorksRepository $worksrepository, ProgramsRepository $programsrepository)
	{
		$this->em = $manager;
		$this->categoryrepository = $categoryrepository;
		$this->courserepository = $courserepository;
		$this->classroomrepository = $classroomrepository;
		$this->userrepository = $userrepository;
		$this->objectrepository = $objectrepository;
		$this->usercourserepository = $usercourserepository;
		$this->worksrepository = $worksrepository;
		$this->programsrepository = $programsrepository;
	}

	/**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

	/**
     * @Route("/courses/page-{page}/{category}", name="course_list", requirements={"page" = "\d+"}, defaults={"page" = 1})
     * @Route("/courses/{finish}/page-{page}", name="course_list_finish", requirements={"page" = "\d+"}, defaults={"page" = 1})
     *
     * Fonction pour afficher la liste des cours (index "Mes Cours")
     *
     */
    public function courseList(Request $request, $finish = null, Category $category = null, $page, PaginatorInterface $paginator)
    {
    	$all = $this->courserepository->findAll();

    	// Mise à jour du statut du cours
    	foreach ($all as $course) {
    		if ($course->getStartAt() >= new \Datetime() && new \Datetime() <= $course->getEndAt()) {
    			$course->setStatus(0);
    		} elseif ($course->getStartAt() <= new \Datetime() && new \Datetime() >= $course->getEndAt()) {
    			$course->setStatus(2);
    		} else {
    			$course->setStatus(1);
    		}
    	}
    	$this->em->flush();

    	// Affichage selon groupe de l'élève
    	/** @var \App\Entity\User $user */
    	$user = $this->getUser();
    	$classroom = $user->getClassroom();

    	if ($classroom !== null) { //élève
			switch ($classroom->getId()) {
				case 1: // CP Isabelle
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 100),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 2: // CE1 Isabelle
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 110),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 3: // CP Véronique et Pascal
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 100),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 4: // CE1 Véronique et Pascal
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 110),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 5: // CE1 Hélène
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 110),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 6: // CE2 Hélène
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 120),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 7: // CE2 Syverine
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 120),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 8: // CM1 Syverine
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 130),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 9: // CM1 Delphine
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 130),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
				case 10: // CM2 Eric
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom, 140),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;

				default:
					$courses = $paginator->paginate(
					$this->courserepository->findByClassroom($classroom),
					$page, /*page number*/
					12 /*limit per page*/
					);
					break;
			}
    	} elseif ($classroom == null && $category !== null) { // vue par catégorie
    		$courses = $paginator->paginate(
	        $this->courserepository->findByCategory($category),
	        $page, /*page number*/
	        9 /*limit per page*/
	        );
    	} else { // prof
    		$courses = $paginator->paginate(
	        $this->courserepository->findAvailable(),
	        $page, /*page number*/
	        12 /*limit per page*/
	        );
    	}

    	// Si affichage des cours terminés
    	if ($finish !== null) {
			$finishCourses = $this->courserepository->findFinish();
		} else {
			$finishCourses = null;
		}


        return $this->render('course/index.html.twig', [
        	'courses' => $courses,
        	'category' => $category,
        	'finishCourses' => $finishCourses
        ]);
    }


    /**
     * @Route("/course/new", name="course_new")
     * @Route("/{category}/course/new", name="course_newCat")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour ajouter un cours dans une catégorie
     */
    public function newCourse(Request $request, Category $category = null, SluggerInterface $slugger)
    {
    	$course = new Course();

    	$form = $this->CreateForm(CourseType::class, $course);

    	if($category) {$form['category']->setData($category);}

    	$form->handleRequest($request);

    	if ($form->isSubmitted() && $form->isValid()) {

    		$course->setStatus(0);

    		$startAt = $form['startAt']->getData()->add(new \DateInterval('PT2H'));
			$course->setStartAt($startAt);
			$endAt = $form['endAt']->getData()->add(new \DateInterval('PT23H59M59S'));
			$course->setEndAt($endAt);

    		$this->em->persist($course);
    		$this->em->flush();

    		$ds = DIRECTORY_SEPARATOR;
    		$path1 = $this->getParameter('images_directory_course').$ds.$course->getId();

    		if (!file_exists($path1) && !is_dir($path1)) {
			 mkdir($path1);
			}

			$path2 = $this->getParameter('files_directory_course').$ds.$course->getId();

    		if (!file_exists($path2) && !is_dir($path2)) {
			 mkdir($path2);
			}

			if ($form['image']->getData() === null) {
    			$category = $this->categoryrepository->find($form['category']->getData());
    			$image = $category->getImage();
				$course->setImage($image);

				$this->em->flush();
    		} else {
				$files = $request->files->get('course');

				foreach ($files as $file) {
					$extension = $file->guessExtension();

					$originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
					$safeFilename = $slugger->slug($originalFilename);
					$fileName = $safeFilename.'-'.uniqid().'.'.$extension;

					if ($file->move($path1, $fileName)) {
						$course->setImage($fileName);

						$this->em->flush();
					}
				}

			}

    		return $this->redirectToRoute('course_newObject', ['course' => $course->getId()]);
    	}

    	$courses = $this->courserepository->findByCategory($category);

        return $this->render('course/newCourse.html.twig', [
        	'courses' => $courses,
            'form' => $form->CreateView(),
        ]);
    }


    /**
     * @Route("/course/{id<\d+>}/edit", name="course_edit")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour éditer un cours
     */
    public function editCourse(Request $request, Course $course, SluggerInterface $slugger)
    {
    	$objects = $course->getCourseObjects();

    	$form = $this->CreateForm(CourseType::class, $course, ['start' => $course->getStartAt()->format('Y-m-d 00:00:00'), 'end' => $course->getEndAt()->format('Y-m-d 00:00:00')]);
    	$form->handleRequest($request);

    	if ($form->isSubmitted() && $form->isValid()) {

    		if ($form['image']->getData() !== null) {

				$ds = DIRECTORY_SEPARATOR;
				// set your uploads directory
				$folder = $course->getId();
				$uploadDir = $this->getParameter('images_directory_course').$ds.$folder;

				// Suppression de l'image sur le serveur
				$prevImage = $uploadDir.$ds.$course->getImage();

				if (file_exists($prevImage)) {
					unlink($prevImage);
				}

    			$files = $request->files->get('course');

				foreach ($files as $file) {
					$extension = $file->guessExtension();

					$originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
					$safeFilename = $slugger->slug($originalFilename);
					$fileName = $safeFilename.'-'.uniqid().'.'.$extension;

					if ($file->move($uploadDir, $fileName)) {
						$course->setImage($fileName);
					}
				}
    		}

			$startAt = $form['startAt']->getData()->add(new \DateInterval('PT2H'));
			$course->setStartAt($startAt);
			$endAt = $form['endAt']->getData()->add(new \DateInterval('PT23H59M59S'));
			$course->setEndAt($endAt);

			if (count($course->getCourseObjects()) == 0) {
				$course->setStatus(0);
			}

    		$this->em->flush();

    		$this->addFlash('success', 'Le cours "'. $course->getTitle() .'" a bien été modifié !');
    		return $this->redirectToRoute('course_edit', ['id' => $course->getId()]);
    	}

        return $this->render('course/editCourse.html.twig', [
            'form' => $form->CreateView(),
            'objects' => $objects,
            'course' => $course
        ]);
	}

	/**
     * @Route("/course/{id<\d+>}/deleteImg", name="course_deleteImg")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour supprimer l'image d'un cours
     */
    public function deleteImageCourse(Course $course)
    {
		$ds = DIRECTORY_SEPARATOR;
		// set your uploads directory
		$folder = $course->getId();
		$uploadDir = $this->getParameter('images_directory_course').$ds.$folder;

		// Suppression de l'image sur le serveur
		$prevImage = $uploadDir.$ds.$course->getImage();

		if (file_exists($prevImage)) {
			unlink($prevImage);
		}

		$image = $course->getCategory()->getImage();
		$course->setImage($image);

		$this->em->flush();

		$this->addFlash('success', 'Image du cours "'.$course->getTitle().'" modifiée avec succès !');

        return $this->redirectToRoute('course_edit', ['id' => $course->getId()]);
    }

    /**
     * @Route("/course/{id<\d+>}/delete", methods="POST", name="course_delete")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour supprimer un cours
     */
    public function deleteCourse(Request $request, Course $course)
    {
        if ($this->isCsrfTokenValid('delete', $request->get('_token'))) {
        	$ds = DIRECTORY_SEPARATOR;
	        // set your uploads directory
	        $folder = $course->getId();
	        $uploadDir = $this->getParameter('images_directory_course').$ds.$folder;

	        foreach ($course->getCourseObjects() as $object) {
	        	$docs = $object->getDocuments();

	    		// Si des documents sont attachés à l'objet
	    		if ($docs !== null) {
	    			foreach ($docs as $doc) {
	    				// Suppression de la relation et du document en base de données
	    				$object->removeDocument($doc);
	    				$this->em->remove($doc);

	    				// Suppression du document dans le dossier sur le serveur
	    				$oldFile = $uploadDir.$ds.$doc->getFilename();
				        if (file_exists($oldFile)) {
				            unlink($oldFile);
				        }
	    			}
	    		}
	    		// Suppression de l'objet
	            $this->em->remove($object);
	        }

            $this->em->remove($course);
	        $this->em->flush();

	        $this->addFlash('success', 'Cours "'.$course->getTitle().'" de la catégorie "'.$course->getCategory()->getTitle().'" supprimé avec succès !');
        } else {
        	$this->addFlash('danger', 'Une erreur est survenue lors de la suppression du cours. Veuillez réessayer.');
        }

        return $this->redirectToRoute('admin_index');
    }

    /**
     * @Route("/course/{id<\d+>}/show-{step}", name="course_show", requirements={"step" = "\d+"}, defaults={"step" = 1})
     *
     * Fonction pour afficher un cours
     */
    public function showCourse(Course $course, int $step, Request $request)
    {
    	$user = $this->getUser();

    	$userCourse = $this->usercourserepository->findOneByCourseAndUser($course, $user);

    	if ($userCourse == null) {

    		$userCourse = new UserCourse();

	    	$userCourse->setUser($user);
	    	$userCourse->setCourse($course);
	    	$userCourse->setProgress(0);
	    	$userCourse->setStep(1);

	    	$this->em->persist($userCourse);
	    	$this->em->flush();
    	}

    	$stepBdd = $userCourse->getStep();

        if ($step != $stepBdd) {
        	return $this->redirectToRoute('course_show', ['id' => $course->getId(), 'step' => $stepBdd]);
		}

		if ($step == count($course->getCourseObjects())) {
			$userCourse->setProgress(100);
			$this->em->flush();
		}

    	$objects = $course->getCourseObjects();

    	$code = array();
    	foreach ($objects as $object) {
    		if ($object->getUrl() !== null) {

				if (strstr($object->getUrl(), ",")) {
					$tempUrls = explode(',', $object->getUrl());
					for ($i=0; $i < count($tempUrls); $i++) {
						$urls[] = trim($tempUrls[$i]);
					}
				} else {
					$urls[] = trim($object->getUrl());
				}
			}
		}

		if (isset($urls)) {
			foreach ($urls as $url) {
				$code[] = '<div class="embed-responsive embed-responsive-16by9 mb-4"><iframe class="embed-responsive-item" src="'.$url.'" allowfullscreen autoplay="false"></iframe></div>';
			}
		}


    	return $this->render('course/show.html.twig', [
    		'course' => $course,
    		'code' => $code,
    		'objects' => $objects,
    		'userCourse' => $userCourse,
    		'step' => $step,
    	]);
    }

    /**
    * @Route("/updateProgress{course}/{step}", name="updateprogress")
    *
    * Fonction pour mettre à jour la progression d'un cours
    */
    public function updateProgress(Course $course, int $step, Request $request)
    {
        $user = $this->getUser();

    	$userCourse = $this->usercourserepository->findOneByCourseAndUser($course, $user);

    	if ($userCourse === null) {
    		$this->addFlash('danger', 'Une erreur s\'est produite : enregistrement progression');
    		return $this->redirectToRoute('course_show', ['id' => $course->getId(), 'step' => $step]);
    	}

        $stepBdd = $userCourse->getStep();

        if ($step !== $stepBdd) {
        	return $this->redirectToRoute('course_show', ['id' => $course->getId(), 'step' => $stepBdd]);
        }

        $stepNext = $step + 1;

        if ($stepNext > count($course->getCourseObjects()) && $course->getIsUploadEnd() == 1 ) {
        	$stepNext = 99;
        }

        $userCourse->setStep($stepNext);

        if ($stepNext == 99 || $step == count($course->getCourseObjects())) {
        	$value = 100;
        } else {
        	$value = round(100 / count($course->getCourseObjects()), 0, PHP_ROUND_HALF_UP);
        }

        if ($userCourse->getProgress() <= 99 && $stepNext != 99) {
        	$progress = $userCourse->getProgress() + $value;
        	$userCourse->setProgress($progress);
        } else {
        	$userCourse->setProgress(100);
        }

    	$this->em->flush();

        return $this->redirectToRoute('course_show', ['id'=> $course->getId(), 'step' => $stepNext]);
     }

     /**
      * @Route("/renderWorks", name="course_works")
      *
      */
     public function renderWorks(Request $request)
     {
     	$work = new Works();

     	$form = $this->createForm(WorksType::class, $work);
     	$form->handleRequest($request);

     	if ($form->isSubmitted() && $form->isValid()) {
     		$work->setUser($this->getUser());
	     	$work->setPostAt(new \Datetime());
	     	$work->setIsRead(0);

	    	$this->em->persist($work);
	    	$this->em->flush();

	        return $this->redirectToRoute('course_editWork', ['work' => $work->getId(), 'add' => 1]);
     	}

     	return $this->render('course/work.html.twig', [
     		'form' => $form->createView(),
     	]);
     }

     /**
      * @Route("/listWorks", name="course_listWorks")
      *
      */
     public function listWorks()
     {
     	$works = $this->worksrepository->findBy(['user' => $this->getUser()->getId()]);

     	return $this->render('course/listworks.html.twig', [
     		'works' => $works,
     	]);
     }


     /**
      * @Route("/showWork{work}", name="course_showWork")
      *
      */
     public function showWork(Works $work, Request $request, EventDispatcherInterface $eventDispatcher)
     {
     	$comment = new Comments();

     	$comments = $work->getComments();

     	$notifs = $work->getNotifications();

     	foreach ($notifs as $notif) {
     		foreach ($notif->getUser() as $userNotif) {
     			if ($userNotif == $this->getUser()) {
	     			$notif->setIsRead(1);
	     			$this->em->flush();
     			}
     		}
     	}

        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

        	if ($form['comment']->getData() !== null) {
        		$user = $this->getUser();

     			$comment->setUser($user);
     			$comment->setPostAt(new \Datetime());
     			$comment->setComment($form['comment']->getData());
     			$work->addComment($comment);

     			$this->em->persist($comment);
            	$this->em->flush();

            	$eventDispatcher->dispatch(new WorkCreatedEvent($work, 1));

            	return $this->render('course/confirmation_workMessage.html.twig', [
	            	'work' => $work,
	            ]);

        	}

        }

    	return $this->render('course/showWork.html.twig', [
            'work' => $work,
            'form' => $form->createView(),
        ]);


     }

    /**
      * @Route("/editWork{work}-{add}", name="course_editWork")
      *
      */
     public function editWork(Works $work, $add = null, Request $request, EventDispatcherInterface $eventDispatcher)
     {
     	$comment = new Comments();

     	$comments = $work->getComments();

        $form = $this->createForm(CommentsType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

        	if (count($work->getFiles()) == 0) {
        		$this->addFlash('danger', 'Tu as oublié de joindre tes documents !');
            	return $this->redirectToRoute('course_editWork', ['work' => $work->getId()]);
        	}

        	if ($form['comment']->getData() !== null) {
        		$user = $this->getUser();

     			$comment->setUser($user);
     			$comment->setPostAt(new \Datetime());
     			$comment->setComment($form['comment']->getData());
     			$work->addComment($comment);

     			$this->em->persist($comment);
            	$this->em->flush();

        	}

        	if ($add != null) {
            	$eventDispatcher->dispatch(new WorkCreatedEvent($work, 0));
        	}

        	return $this->render('course/confirmation_work.html.twig', [
            	'work' => $work,
            ]);
        }

    	return $this->render('course/addWork.html.twig', [
            'work' => $work,
            'add' => $add,
            'form' => $form->createView(),
        ]);

     }


     /**
    * @Route("/uploadFilesWork/{work}", name="uploadFilesWork")
    *
    * Fonction pour télécharger les documents d'un rendu de devoir en Ajax
    */
    public function uploadFilesWork(Works $work, Request $request, SluggerInterface $slugger) {
        $output = array('uploaded' => false);
        $files = $request->files->get('file');

        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
        $userId = $this->getUser()->getId();

        $uploadDir = $this->getParameter('files_directory_course').$ds.$userId;

        foreach ($files as $file) {
    		$extension = $file->guessExtension();

    		$originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $fileName = $safeFilename.'-'.uniqid().'.'.$extension;

			if (!file_exists($uploadDir) && !is_dir($uploadDir)) {
			 mkdir($uploadDir);
			}

			if ($file->move($uploadDir, $fileName)) {
				// create and set this image
                $file = new Files();

            	$mimeTypes = new MimeTypes();
				$mimeType = $mimeTypes->guessMimeType($uploadDir.$ds.$fileName);

                $file->setName($fileName);
                $file->setFiletype($mimeType);
                $file->setUser($this->getUser());

                $work->addFile($file);

				// save the uploaded filename to database
				$this->em->persist($file);
				$this->em->flush();
				$output['uploaded'] = true;
	            $output['fileName'] = $fileName;
	            $output['success'] = 'Fichier chargé !';
	        }

			unset($file);

	    }

        return new JsonResponse($output);
     }

    /**
    * @Route("/getfiles{work}", name="getworkFiles")
    *
    * Fonction pour récupérer les documents d'un rendu de devoir en Ajax
    */
    public function getWorkFiles(Works $work, Request $request)
    {

        $userId = $this->getUser()->getId();

        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
        $uploadDir = $this->getParameter('files_directory_course').$ds.$userId;

        $filesWork = $work->getFiles();

        $result  = array();

        $files = scandir($uploadDir);

        if ( false!==$files ) {
            foreach ($files as $file) {
            	foreach ($filesWork as $fileWork) {
            		if ( '.'!=$file && '..'!=$file && $file === $fileWork->getName()) {
	                    $obj['name'] = $file;
	                    $obj['size'] = filesize($uploadDir.$ds.$file);
	                    $obj['uploaded'] = true;
	                    $result[] = $obj;
	                }
            	}

            }
        }

       return new JsonResponse($result);
     }

    /**
    * @Route("/deleteWorkFiles{work}", name="deleteWorkFiles")
    *
    * Fonction pour supprimer les documents d'un rendu de devoir en Ajax
    */
    public function deleteWork(Works $work, Request $request) {

        $userId = $this->getUser()->getId();

        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
        $uploadDir = $this->getParameter('files_directory_course').$ds.$userId;

        $result = $request->query->get('name');

        $files = $work->getFiles();

        foreach ($files as $file) {
            if ($result == $file->getName()) {
                $work->removeFile($file);
                $this->em->remove($file);
            }
        }

        $oldFile = $uploadDir.$ds.$result;
        if (file_exists($oldFile)) {
            unlink($oldFile);
        }

        $response = array('success' => 'Delete OK', 'uploaded' => true);

        $this->em->flush();

       return new JsonResponse($response);
     }

    /**
     * @Route("/category", name="course_category")
     * @Route("/category/{id}/edit", name="course_categoryEdit")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour ajouter ou modifier une catégorie
     */
    public function category(Request $request, Category $category = null)
    {
    	$edit = true;

    	if($category === null) {$category = new Category(); $edit = false;}

    	$form = $this->CreateForm(CategoryType::class, $category);
    	$form->handleRequest($request);

    	if ($form->isSubmitted() && $form->isValid()) {
    		$this->em->persist($category);
    		$this->em->flush();

    		if ($edit === true) {
    			$this->addFlash('success', 'La catégorie "'. $category->getTitle() .'" a bien été modifiée !');
    		} else {
    			$this->addFlash('success', 'La catégorie "'. $category->getTitle() .'" a bien été créée !');
    		}

    		return $this->redirectToRoute('course_category');
    	}

    	$categories = $this->categoryrepository->findAll();

        return $this->render('course/category.html.twig', [
        	'edit' => $edit,
        	'categories' => $categories,
            'form' => $form->CreateView(),
        ]);
    }

    /**
     * @Route("/classroom", name="course_classroom")
     * @Route("/classroom/{id}/edit", name="course_classroomEdit")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour ajouter ou modifier un groupe d'élève
     */
    public function CourseClassroom(Request $request, Classroom $class = null)
    {
    	$edit = true;

    	if($class === null) {$class = new Classroom(); $edit = false;}

    	$form = $this->CreateForm(ClassroomType::class, $class);
    	$form->handleRequest($request);

    	if ($form->isSubmitted() && $form->isValid()) {
			// On parcoure les élèves cochés et on les attribue à la classe
			foreach ($form['user']->getData() as $userForm) {
		    	$user = $this->userrepository->find($userForm);

		  	  	$user->setClassroom($class);
		  	  	$class->addUser($user);
		  	}

		    $this->em->persist($class);
    		$this->em->flush();
    	}

        return $this->render('course/class.html.twig', [
        	'edit' => $edit,
        	'class' => $class,
            'form' => $form->CreateView(),
        ]);
    }

    /**
     * @Route("/course-{course<\d+>}/newObject", name="course_newObject")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour ajouter un objet à un cours
     */
    public function newObject(Request $request, Course $course)
    {
    	$courseObj = new CourseObject();

    	$form = $this->CreateForm(CourseObjectType::class, $courseObj);
    	$form->handleRequest($request);

    	if ($form->isSubmitted() && $form->isValid()) {

			$courseObj->setCourse($course);

	     	$courseId = $course->getId();
	     	$prev = $this->objectrepository->findLast($courseId);

	     	if ($prev) {
	     		$lastRank = $prev->getRanking();
	     		$courseObj->setRanking($lastRank + 1);
	     	} else {
	     		$courseObj->setRanking(0);
			}

			if ($form['url']->getData() !== null) {
    			if (strstr($form['url']->getData(), "watch?v=")) {
    				$url = str_replace('watch?v=', 'embed/', $form['url']->getData());
    				$courseObj->setUrl($url);
    			} elseif (strstr($form['url']->getData(), "youtu.be")) {
					$url = str_replace('youtu.be', 'www.youtube.com/embed', $form['url']->getData());
					$courseObj->setUrl($url);
				}
    		}

			$this->em->persist($courseObj);
			$this->em->flush();

			$this->addFlash('success', 'Objet créé avec succès !');

			if ($form->getClickedButton() === $form->get('upload')) {
				return $this->redirectToRoute('course_addDocs', ['course' => $course->getId(), 'object' => $courseObj->getId()]);
			} else {
				return $this->redirectToRoute('course_edit', ['id' => $course->getId()]);
			}
    	}

    	return $this->render('course/newObject.html.twig', [
    		'form' => $form->CreateView(),
    		'object' => $courseObj,
    		'course' => $course
    	]);
    }

    /**
     * @Route("/course-{course<\d+>}/object-{object<\d+>}/edit", name="course_editObject")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour éditer l'objet d'un cours
     */
    public function editObject(Request $request, Course $course, CourseObject $object)
    {

    	$form = $this->CreateForm(CourseObjectType::class, $object);
    	$form->handleRequest($request);

    	if ($form->isSubmitted() && $form->isValid()) {

    		if ($form['url']->getData() !== null) {
    			if (strstr($form['url']->getData(), "watch?v=")) {
    				$url = str_replace('watch?v=', 'embed/', $form['url']->getData());
    				$object->setUrl($url);
    			} elseif (strstr($form['url']->getData(), "youtu.be")) {
					$url = str_replace('youtu.be', 'www.youtube.com/embed', $form['url']->getData());
					$object->setUrl($url);
				}
    		}

			$this->em->flush();

			$this->addFlash('success', 'Objet modifié avec succès !');

			return $this->redirectToRoute('course_edit', ['id' => $course->getId()]);

    	}

    	return $this->render('course/editObject.html.twig', [
    		'form' => $form->CreateView(),
    		'object' => $object,
    		'course' => $course
    	]);
    }

    /**
     * @Route("/course-{course<\d+>}/object-{object<\d+>}/delete", name="course_deleteObject")
     * @isGranted("ROLE_TEACHER")
     *
     * Fonction pour supprimer l'objet d'un cours
     */
    public function deleteObject(Request $request, CourseObject $object, Course $course)
    {
    	if ($this->isCsrfTokenValid('delete'. $object->getId(), $request->get('_token'))) {
    		$ds = DIRECTORY_SEPARATOR;
	        // set your uploads directory
	        $folder = $object->getCourse()->getId().$ds.$object->getId();
	        $uploadDir = $this->getParameter('images_directory_course').$ds.$folder;

    		$docs = $object->getDocuments();

    		// Si des documents sont attachés à l'objet
    		if ($docs !== null) {
    			foreach ($docs as $doc) {
    				// Suppression de la relation et du document en base de données
    				$object->removeDocument($doc);
    				$this->em->remove($doc);

    				// Suppression du document dans le dossier sur le serveur
    				$oldFile = $uploadDir.$ds.$doc->getFilename();
			        if (file_exists($oldFile)) {
			            unlink($oldFile);
			        }
    			}
    		}
    		// Suppression de l'objet
            $this->em->remove($object);

            // Réorganisation de l'ordre d'affichage
            $rank = $object->getRanking();
	     	$courseId = $course->getId();
	     	$allObjects = $course->getCourseObjects();

	     	$allRanks = array();
	     	foreach ($allObjects as $obj) {
	     		$allRanks[] = $obj->getRanking();
	     	}

	     	$higherRank = max($allRanks);

	     	for ($i=$rank; $i < $higherRank ; $i++) {
	     		$next = $this->objectrepository->findAround($courseId, $i + 1);
	            if ($next) {
	            	if ($next->getRanking() !== $i) {
	            		$next->setRanking($i);
	            	}
	            }
	     	}


            $this->em->flush();
            $this->addFlash('success', 'L\'objet "'. $object->getName() .'" a bien été supprimé !');
        } else {
        	$this->addFlash('danger', 'Une erreur est survenue ! Rechargez la page et réessayez.');
        }
        return $this->redirectToRoute('course_edit', ['id' => $course->getId()]);
    }

    /**
     * @Route("/course-{course<\d+>}/object{object<\d+>}/newDocs", name="course_addDocs")
     * @isGranted("ROLE_TEACHER")
     *
     * Rendu de la page pour charger les documents d'un objet
     */
    public function addDocuments(Course $course, CourseObject $object)
    {
    	return $this->render('course/newDocuments.html.twig', [
    		'course' => $course,
    		'object' => $object
    	]);
    }


    /**
    * @Route("/fileuploadhandler{course}/{object}", name="fileuploadhandler")
    * @isGranted("ROLE_TEACHER")
    *
    * Fonction pour télécharger les documents d'un objet en Ajax
    */
    public function fileUploadHandler(Course $course, CourseObject $object = null, Request $request, SluggerInterface $slugger) {
		$output = array();
		$output['uploaded'] = false;
		$files = $request->files->get('file');


        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory

        $objId = $object->getId();

        $folder = $course->getId().$ds.$objId;
        $uploadDir = $this->getParameter('images_directory_course').$ds.$folder;

        foreach ($files as $file) {

    		$extension = $file->guessExtension();

    		$originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $fileName = $safeFilename.'-'.uniqid().'.'.$extension;

			if (!file_exists($uploadDir) && !is_dir($uploadDir)) {
			 mkdir($uploadDir);
			}

			if ($file->move($uploadDir, $fileName)) {
				// create and set this image
                $doc = new Documents();

            	$mimeTypes = new MimeTypes();
				$mimeType = $mimeTypes->guessMimeType($uploadDir.$ds.$fileName);

                $doc->setFilename($fileName);
                $doc->setObject($object);
                $doc->setFiletype($mimeType);

				// save the uploaded filename to database
				$this->em->persist($doc);
				$this->em->flush();
				$output['uploaded'] = true;
	            $output['fileName'] = $fileName;
	            $output['success'] = 'Fichier chargé !';
	        }

		 	unset($file);
	    }

        return new JsonResponse($output);
     }

    /**
    * @Route("/getdocuments{object}", name="getdocuments")
    * @isGranted("ROLE_TEACHER")
    *
    * Fonction pour récupérer les documents d'un objet en Ajax
    */
    public function getDocuments(CourseObject $object = null, Request $request) {

        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
        $folder = $object->getCourse()->getId().$ds.$object->getId();
        $uploadDir = $this->getParameter('images_directory_course').$ds.$folder;

        $result  = array();

        $files = scandir($uploadDir);
        if ( false!==$files ) {
            foreach ( $files as $file ) {
                if ( '.'!=$file && '..'!=$file) {
                    $obj['name'] = $file;
                    $obj['size'] = filesize($uploadDir.$ds.$file);
                    $obj['uploaded'] = true;
                    $result[] = $obj;
                }
            }
        }

       return new JsonResponse($result);
     }

    /**
    * @Route("/deletedocs{object}", name="deletedocs")
    * @isGranted("ROLE_TEACHER")
    *
    * Fonction pour supprimer les documents d'un objet en Ajax
    */
    public function deleteDocuments(CourseObject $object, Request $request) {

        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
        $folder = $object->getCourse()->getId().$ds.$object->getId();
        $uploadDir = $this->getParameter('images_directory_course').$ds.$folder;

        $result = $request->query->get('name');

        $docs = $object->getDocuments();

        foreach ($docs as $doc) {
            if ($result == $doc->getFilename()) {
                $object->removeDocument($doc);
                $this->em->remove($doc);
            }
        }

        $oldFile = $uploadDir.$ds.$result;
        if (file_exists($oldFile)) {
            unlink($oldFile);
        }

        $response = array('success' => 'Delete OK', 'uploaded' => true);

        $this->em->flush();

       return new JsonResponse($response);
     }

     /**
      * @Route("/moveObject{object}-{direction}", name="moveObject")
      * @isGranted("ROLE_TEACHER")
      *
      * Fonction pour modifier l'ordre d'affichage des objets en Ajax
      */
     public function moveObject(CourseObject $object, $direction)
     {
     	$rank = $object->getRanking();
     	$rankPlus = $rank + 1;
     	$rankMinus = $rank - 1;
     	$courseId = $object->getCourse()->getId();
     	$prev = $this->objectrepository->findAround($courseId, $rankMinus);
     	$next = $this->objectrepository->findAround($courseId, $rankPlus);

     	if ($direction == "up") {

			if ($prev->getRanking() == $rank) {
				$this->addFlash('danger', 'Erreur : Deux objets ont le même numéro !');
				return $this->redirectToRoute('course_edit', ['id' => $object->getCourse()->getId()]);
			}

     		$prev->setRanking($rank);
     		$object->setRanking($rankMinus);

     	} else if ($direction == "down") {

			if ($next->getRanking() == $rank) {
				$this->addFlash('danger', 'Erreur : Deux objets ont le même numéro !');
				return $this->redirectToRoute('course_edit', ['id' => $object->getCourse()->getId()]);
			}

     		$next->setRanking($rank);
     		$object->setRanking($rankPlus);

     	} else {
     		return false;
     	}

     	$this->em->flush();

     	$response = array('success' => 'OK');

     	return new JsonResponse($response);
	 }

	/**
     * Fonction pour afficher les programmes
     *
     * @Route("/programs", name="view_programs")
     */
    public function viewPrograms()
    {
		$programs = $this->programsrepository->findLastPrograms();

		return $this->render('course/programs.html.twig', [
    		'page' => $programs,
    	]);
	}
}
