<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller;

use App\Form\Type\ChangePasswordType;
use App\Form\UserType;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\UserCourseRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * Controller used to manage current user.
 *
 * @Route("/profile")
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 *
 * @author Romain Monteil <monteil.romain@gmail.com>
 */
class UserController extends AbstractController
{
    private $manager;

    private $usercourserepository;

    public function __construct(EntityManagerInterface $manager, UserCourseRepository $usercourserepository) 
    {
        $this->em = $manager;
        $this->usercourserepository = $usercourserepository;
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/profile", name="user_profile")
     */
    public function index()
    {
        $user = $this->getUser();

        $userCourses = $this->usercourserepository->findWeekUser($user);

        $progress = 0;
        foreach ($userCourses as $userCourse) {
            $progress += $userCourse->getProgress();
        }

        $mid = (count($userCourses) > 0) ? round(($progress / count($userCourses))) : 0 ;

        $nbrFinish = count($this->usercourserepository->findFinishUser($user));

        return $this->render('user/profile.html.twig', [
            'user' => $user,
            'mid' => $mid,
            'nbrFinish' => $nbrFinish,
        ]);
    }

    /**
     * @Route("/edit", methods="GET|POST", name="user_edit")
     */
    public function edit(Request $request): Response
    {
        $user = $this->getUser();

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            $this->addFlash('success', 'user.updated_successfully');

            return $this->redirectToRoute('user_edit');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/avatar", methods="GET|POST", name="user_avatar")
     */
    public function avatar(Request $request): Response
    {
        $user = $this->getUser();

        return $this->render('user/avatar.html.twig', [
            'user' => $user,
        ]);
    }

    /**
    * @Route("/uploadAvatar{user}", name="uploadavatar")
    */
    public function uploadAvatar(User $user, Request $request) {
        $output = array('uploaded' => false);
        $file = $request->files->get('file');

        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
              
        $userId = $user->getId();
        
        $folder = $userId;
        $uploadDir = $this->getParameter('images_directory_user').$ds.$folder;

        $extension = $file->guessExtension();
        $fileName = $this->generateUniqueFileName().'.'.$extension;

        if (!file_exists($uploadDir) && !is_dir($uploadDir)) {
         mkdir($uploadDir);
        }
        if ($file->move($uploadDir, $fileName)) { 
            // create and set this image 
            $user->setAvatar($fileName);
            
            // save the uploaded filename to database
            $this->em->persist($user);
            $this->em->flush();
            $output['uploaded'] = true;
            $output['fileName'] = $fileName;
            $output['success'] = 'Fichier chargé !';
        }
        
        return new JsonResponse($output);
     }

     /**
    * @Route("/getavatar{user}", name="getavatar")
    */
    public function getAvatar(User $user, Request $request) {
        
        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
        $folder = $user->getId();
        $uploadDir = $this->getParameter('images_directory_user').$ds.$folder;
                                                               
        $result  = array();
     
        $files = scandir($uploadDir);
        if ( false!==$files ) {
            foreach ( $files as $file ) {
                if ( '.'!=$file && '..'!=$file) {
                    $obj['name'] = $file;
                    $obj['size'] = filesize($uploadDir.$ds.$file);
                    $obj['uploaded'] = true;
                    $result[] = $obj;
                }
            }
        }
        
       return new JsonResponse($result);
     }

     /**
    * @Route("/deleteavatar{user}", name="deleteavatar")
    */
    public function deleteAvatar(User $user, Request $request) {
        
        $ds = DIRECTORY_SEPARATOR;
        // set your uploads directory
        $folder = $user->getId();
        $uploadDir = $this->getParameter('images_directory_user').$ds.$folder;
                                                               
        $result = $request->query->get('name');

        if ($result == $user->getAvatar()) {
            $user->setAvatar(null);
        }
        
        $oldFile = $uploadDir.$ds.$result;
        if (file_exists($oldFile)) {
            unlink($oldFile);
        }        

        $response = array('success' => 'Delete OK', 'uploaded' => true);

        $this->em->flush();
        
       return new JsonResponse($response);
     }

    /**
     * @Route("/change-password", methods="GET|POST", name="user_change_password")
     */
    public function changePassword(Request $request, UserPasswordEncoderInterface $encoder): Response
    {
        $user = $this->getUser();

        $form = $this->createForm(ChangePasswordType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword($encoder->encodePassword($user, $form->get('newPassword')->getData()));

            $this->em->flush();

            return $this->redirectToRoute('security_logout');
        }

        return $this->render('user/change_password.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}
